name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Change to the Project Directory
      run: cd ./Practical\ 1_Temperature\ Conversion/

    - name: Grant execute permission for gradlew
      run: chmod +x ./Practical\ 1_Temperature\ Conversion/gradlew

    - name: Build with Gradle
      run: ./Practical\ 1_Temperature\ Conversion/gradlew build

    - name: Run unit tests
      run: ./Practical\ 1_Temperature\ Conversion/gradlew test
