name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # No need to change directory with 'cd'
    # Instead, specify 'working-directory' for each step as needed

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: Practical\ 1_Temperature\ Conversion/

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: Practical\ 1_Temperature\ Conversion/

    - name: Run unit tests
      run: ./gradlew test
      working-directory: Practical\ 1_Temperature\ Conversion/
