name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-daemon

    - name: Run Unit Tests
      run: ./gradlew test --no-daemon
